version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    volumes:
      - ./maria_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_app
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_pwd
    ports:
      - 3306:3306
    restart: unless-stopped
